HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 104
ETag: W/"68-JEqoBZ/DnH2cA/zP6N42n0HNLfs"
Date: Mon, 24 Oct 2022 09:26:34 GMT
Connection: close

<p>Phonebook has info for 4</p><p>Mon Oct 24 2022 11:25:35 GMT+0200 (Eastern European Standard Time)</p>